version: '2'
services:
    finance-app:
        image: finance
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://finance-mysql:3306/finance?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    finance-mysql:
        extends:
            file: mysql.yml
            service: finance-mysql
